#!/usr/bin/env bash
set -euo pipefail

DATA_DIR="${NEURAI_DATADIR:-/data}"
mkdir -p "$DATA_DIR"

cat > "$DATA_DIR/neurai.conf" <<EOF
# Generated by Docker entrypoint — do not edit manually
testnet=${NEURAI_TESTNET:-1}

# RPC
rpcuser=${NEURAI_RPC_USER:-neurai}
rpcpassword=${NEURAI_RPC_PASSWORD:-changeme}
rpcallowip=${NEURAI_RPC_ALLOW_IP:-0.0.0.0/0}
rpcport=${NEURAI_RPC_PORT:-19101}
rpcservertimeout=${NEURAI_RPC_TIMEOUT:-240}
rpcworkqueue=${NEURAI_RPC_WORKQUEUE:-64}
rpcthreads=${NEURAI_RPC_THREADS:-8}
server=1

# Network
listen=${NEURAI_LISTEN:-0}
rest=${NEURAI_REST:-1}

# Indexes
txindex=${NEURAI_TXINDEX:-1}
assetindex=${NEURAI_ASSETINDEX:-1}
addressindex=${NEURAI_ADDRESSINDEX:-1}
timestampindex=${NEURAI_TIMESTAMPINDEX:-1}
spentindex=${NEURAI_SPENTINDEX:-1}
pubkeyindex=${NEURAI_PUBKEYINDEX:-1}

EOF

if [ "${NEURAI_ZMQ_ENABLED:-0}" = "1" ]; then
  ZMQ_BIND="${NEURAI_ZMQ_BIND:-tcp://0.0.0.0:28332}"
  cat >> "$DATA_DIR/neurai.conf" <<EOF

# ZMQ
zmqpubhashblock=${NEURAI_ZMQ_PUB_HASHBLOCK:-$ZMQ_BIND}
zmqpubrawtx=${NEURAI_ZMQ_PUB_RAWTX:-$ZMQ_BIND}
zmqpubhashtx=${NEURAI_ZMQ_PUB_HASHTX:-$ZMQ_BIND}
EOF
fi

if [ "${NEURAI_DEPIN_ENABLED:-0}" = "1" ]; then
  # Protocol 2 (DePIN-Test branch): the service is served on the node's RPC
  # port only, its pool key comes from the node's wallet, and the token owner
  # must have vouched for that key. Fail here, with the reason, rather than let
  # neuraid InitError in a restart loop.
  if [ -z "${NEURAI_DEPIN_TOKEN:-}" ]; then
    echo "[entrypoint] ERROR: NEURAI_DEPIN_ENABLED=1 but NEURAI_DEPIN_TOKEN is empty - set a messaging token." >&2
    exit 1
  fi
  if [ "${NEURAI_DISABLE_WALLET:-1}" = "1" ]; then
    echo "[entrypoint] ERROR: NEURAI_DEPIN_ENABLED=1 requires NEURAI_DISABLE_WALLET=0: the pool key is derived from the node's (dedicated, unencrypted, legacy BIP44) wallet." >&2
    exit 1
  fi
  if [ -z "${NEURAI_DEPIN_POOLKEYSIG:-}" ]; then
    echo "[entrypoint] ERROR: NEURAI_DEPIN_ENABLED=1 requires NEURAI_DEPIN_POOLKEYSIG: start once with NEURAI_DEPIN_ENABLED=0, run 'neurai-cli depinpoolpkey', have the token owner signmessage \"DEPIN-POOLKEY|<token>|<pubkey>\", then set the signature." >&2
    exit 1
  fi
  cat >> "$DATA_DIR/neurai.conf" <<EOF

# Supported only by the DePIN-Test node branch (DePIN protocol 2).
# Served over the RPC port above; there is no separate DePIN listener.
depinmsg=1
depinmsgtoken=${NEURAI_DEPIN_TOKEN}
depinpoolkeysig=${NEURAI_DEPIN_POOLKEYSIG}
depinmsgsize=${NEURAI_DEPIN_MAX_MESSAGE_SIZE:-1024}
depinmsgexpire=${NEURAI_DEPIN_MESSAGE_EXPIRY:-168}
depinpoolsize=${NEURAI_DEPIN_MAX_POOL_SIZE:-100}
EOF
  if [ -n "${NEURAI_DEPIN_WALLET:-}" ]; then
    echo "depinwallet=${NEURAI_DEPIN_WALLET}" >> "$DATA_DIR/neurai.conf"
  fi
fi

cat >> "$DATA_DIR/neurai.conf" <<EOF

# Wallet — disabled by default, set NEURAI_DISABLE_WALLET=0 to enable.
# A DePIN service node needs one (dedicated, unencrypted, legacy BIP44, no
# funds): it is where the pool key comes from.
disablewallet=${NEURAI_DISABLE_WALLET:-1}

# Log — shrink debug.log automatically when it grows too large
shrinkdebugfile=1

# Docker — run in foreground (daemon=1 breaks the container lifecycle)
daemon=0
EOF

echo "[entrypoint] neurai.conf written to $DATA_DIR/neurai.conf"
exec neuraid -datadir="$DATA_DIR" "$@"
